Add c100 to CODEOWNERS
hmcts/sds-flux-config pull request #2240
Opened 2022-09-13 09:25 UTC by WillTaylor22

2022-09-13 09:25 UTC, timja requested changes
this should be your team not plat-ops

2022-09-13 10:40 UTC, adusumillipraveen approved these changes

2022-09-13 11:00 UTC, timja approved these changes

2022-09-29 10:45 UTC, msl8r approved these changes

2022-09-29 10:50 UTC, merged