Added pip data man to sbox
hmcts/sds-flux-config pull request #2789
Opened 2023-03-20 13:18 UTC by joshblackmoor

### Change description ###

Added pip data man to sbox.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-03-20 14:35 UTC, ChrisS1512 requested changes

2023-03-20 14:35 UTC, ChrisS1512 commented on apps/pip/sbox/base/kustomization.yaml
> +apiVersion: kustomize.config.k8s.io/v1beta1
I think you'll also need a cluster file here too due to this file : https://github.com/hmcts/sds-flux-config/blob/master/apps/pip/base/kustomize.yaml

looking for the cluster

2023-03-20 14:58 UTC, ChrisS1512 approved these changes

2023-03-21 08:37 UTC, jordankainos approved these changes
lgtm

2023-03-21 08:45 UTC, merged