juror: add juror-public
hmcts/sds-flux-config pull request #3747
Opened 2023-10-27 12:53 UTC by nperry-cgi

### Jira link (if applicable)

### Change description ###

### Checklist

- [ x ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

2023-10-27 13:56 UTC, Ianrfisher requested changes
Just one very minor comment

2023-10-27 13:56 UTC, Ianrfisher commented on apps/juror/stg/base/kustomization.yaml
> +  - path: ../../juror-public/stg.yaml
OCD - argh - can you swap order to match other files please

2023-10-27 14:21 UTC, Ianrfisher approved these changes

2023-11-03 15:03 UTC, subtitleuk approved these changes

2023-11-03 15:03 UTC, merged